第2回目課題提出：数あてクイズ
ishimine530/raisetech-java pull request #1
Opened 2022-09-06 16:14 UTC by ishimine530

# 第2回目課題
数あてクイズを作成しました。

## クイズ内容説明
・乱数(0~9)を3つ生成し、3つの数字のうち、どれか1つの数字を当てる。
・5回まで回答可能。※1桁の数字以外が入力された場合はカウントされない。

## コードについて
・for文、if文、while文を使用。
・練習として配列に乱数を格納。（Listは次回の課題に持ち越し）
・乱数の重複について考慮なし。

## 実行結果
<img src=https://user-images.githubusercontent.com/88490921/188683810-41d946c6-4074-49e1-bd3b-863ae6190087.png  width=50%>
<img src=https://user-images.githubusercontent.com/88490921/188683839-daeb50fa-f5dd-4e51-80b1-a684b08ff86b.png  width=50%>

2022-09-08 00:24 UTC, YudaiNoda3576 reviewed
コメントしています！
IDEの設定で保存時に改行を含む設定ができるので併せてそちらも設定しておいてください〜:pray:

2022-09-08 00:24 UTC, YudaiNoda3576 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +	public static int[] comanswer() {
メソッドの命名についてですが、メソッドの名前を見たときにパッとそれが何をするメソッドなのかが分かることが理想的です！
今回だと、`generateNumberArray`とかなんですかね🤔

2022-09-08 00:24 UTC, YudaiNoda3576 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +				if (num == input) {
ここの正誤判定なんですが、`java.util.Array` の `contains` メソッドを使用すると簡潔に記述できるので試しにチャレンジしてみてください！（内部の挙動を変えずにコードをより良いものにする作業をリファクタリングと言います）

2022-09-08 00:24 UTC, YudaiNoda3576 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +	public static int[] comanswer() {
また、おそらく今回はメソッドを定義することを練習としてやっていただいてると思うので今後の参考程度に知っておいて欲しいことをお伝えしておきます！

このメソッドの振る舞いとしては、Randuomクラスのインスタンスを作成してintsメソッドを呼び出しているだけになるのでメソッドに切り分けなくても良いかなと思います！

例えば生成した乱数配列に対して何かしらの計算処理を入れるようなロジックが絡んできた場合にメソッドへの切り出しを検討するのが良いかなと思います！

2022-09-15 12:40 UTC, ishimine530 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +	public static int[] comanswer() {
メソッド名について失礼しました。
もっとわかりやすい命名をするべきでした。

また、メソッドの振る舞いについてご教授いただきありがとうございます。
ご認識の通り、乱数生成のメソッドは練習として定義していました。
しかし、メソッドに切り出す場合の判断基準を理解できていなかったため不要なメソッドでした。

今回の修正で乱数生成メソッドをやめ、mainメソッドに記載しました。
ご確認よろしくお願いいたします。

2022-09-15 12:40 UTC, ishimine530 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +				if (num == input) {
`contains`メソッドを使用した正誤判定に修正しました。

`contains`メソッドを使用した正誤判定にするため、int配列をリストへ変換する処理を追加しております。
そちらもあわせてご確認をお願いいたします。

＞`contains`メソッドを使用して正誤判定を簡潔に記載する
はじめて`contains`メソッドを使用するため、指摘内容をくみ取れていない修正になっている場合はご指摘をお願いします。

2022-09-16 01:00 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-09-16 01:00 UTC, YudaiNoda3576 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +		List<Integer> generateNumbers = new ArrayList<>(numbers.length);
`generateNumbers`という命名だと動詞 + 名詞になって数を生成するみたいな意味になるのでメソッドっぽいです！
今回でいくと、数のListなので単純に`numbersList` とかの方が素直な感じがするのですがいかがでしょうか？🤔

2022-09-16 01:00 UTC, YudaiNoda3576 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +		List<Integer> generateNumbers = new ArrayList<>(numbers.length);
```suggestion
        List<Integer> numberList = new Random().ints(3, 0, 9).collect(ArrayList::new, ArrayList::add, ArrayList::addAll);
```

不細工ではありますが、L.16とL.19をワンライナーで書くこともできるので参考までに！

2022-09-16 01:00 UTC, YudaiNoda3576 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +		for (int i : numbers) {
ここも練習を兼ねてStreamAPIを使ってみると良いかもです！（余裕があればで大丈夫です）

2022-09-26 13:38 UTC, ishimine530 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +		List<Integer> generateNumbers = new ArrayList<>(numbers.length);
メソッド名、変数名を付けるのが下手なようです…。
`generateNumbers`を翻訳にかけたら「数字を生成する」になったので、確かにメソッドっぽいと感じました。
ご提案いただいた通り`numbersList`が適切だと思いましたので、`numbersList`へ修正しました。
ご確認をお願いいたします。
54acd043248ed62661049ea748ad13ad97e356b1

2022-09-26 13:39 UTC, ishimine530 commented on KazuateQuiz/src/kazuate/KazuateQuiz.java
> +		for (int i : numbers) {
Steamを使用したコードに修正しました！
ご確認よろしくお願いいたします。
4ab4304b98b014a8248d7e8cbd53109c7c759885

2022-09-26 14:01 UTC, ishimine530 commented
@YudaiNoda3576 

下記の①②がコンソールに順不同で出力される件についてです。
【while処理部分】
　①0～9の範囲で入力してください。
　②●回目：1桁の数字を入力してください。

質問へのご対応ありがとうございました。
以下、「順不同で出力される原因」「標準出力と標準エラー出力の違い」「修正対応」について記載いたしました。

**順不同で出力される原因**
コンソールでは、標準出力と標準エラー出力が非同期に出力されるため、順不同となることがある。

**標準出力と標準エラー出力の違い**
・標準出力
　プログラムから文字列などのデータを表示し、ディスプレイへ出力すること
・標準エラー出力
　エラーメッセージをディスプレイへ出力すること

**修正対応**
`System.out`で出力するように修正しました。
flush関数で出力を制御するという方法もあると小山さんから教えていただきましたが
今後の学習で`System.out`を使用することはほとんどないとのことなので
単純に`System.out`で出力するよういたしました。

ご確認よろしくお願いいたします。
7dc756f2a989cda4c6784e671f6b6ce4ec6835b4

2022-09-26 14:04 UTC, ishimine530 commented
@YudaiNoda3576 

01のような先頭に0が付く数字を1桁として扱わないようにする修正を行いました。
ご確認よろしくお願いいたします。
5a7b27c2b9f23716cbd714d4902a82ecb61d7d74

2022-09-26 22:22 UTC, YudaiNoda3576 commented
@ishimine530 
確認しました！
良さそうです！マージしてください！
お疲れ様でした:smile:

2022-09-27 00:34 UTC, merged